name: barra
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.9.1
  firebase_auth_web: ^5.11.5
  firebase_core_web: ^2.17.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.0 # Agregar esta línea
  google_maps_flutter: ^2.0.10 
  url_launcher: ^6.0.0 
  provider: ^6.0.3
  shared_preferences: ^2.0.6


 
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true

  