// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiQWvixcFZHAXXn2Q7DG0hblss7i7Fzuw',
    appId: '1:93036604998:web:2ba5da8356291591672447',
    messagingSenderId: '93036604998',
    projectId: 'nuevo-e4ca2',
    authDomain: 'nuevo-e4ca2.firebaseapp.com',
    storageBucket: 'nuevo-e4ca2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHccn9YAwqoCMrcczZmafpRqzkNu_DnB8',
    appId: '1:93036604998:android:024b3297d231b3ee672447',
    messagingSenderId: '93036604998',
    projectId: 'nuevo-e4ca2',
    storageBucket: 'nuevo-e4ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWL8SIZwZomKILf1FBUMH0RGlSpwtY5y0',
    appId: '1:93036604998:ios:aad115557c8a81b7672447',
    messagingSenderId: '93036604998',
    projectId: 'nuevo-e4ca2',
    storageBucket: 'nuevo-e4ca2.appspot.com',
    iosBundleId: 'com.example.barra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWL8SIZwZomKILf1FBUMH0RGlSpwtY5y0',
    appId: '1:93036604998:ios:aad115557c8a81b7672447',
    messagingSenderId: '93036604998',
    projectId: 'nuevo-e4ca2',
    storageBucket: 'nuevo-e4ca2.appspot.com',
    iosBundleId: 'com.example.barra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiQWvixcFZHAXXn2Q7DG0hblss7i7Fzuw',
    appId: '1:93036604998:web:007b678555b15ef6672447',
    messagingSenderId: '93036604998',
    projectId: 'nuevo-e4ca2',
    authDomain: 'nuevo-e4ca2.firebaseapp.com',
    storageBucket: 'nuevo-e4ca2.appspot.com',
  );

}